---
title: 'UTSSRP - Causal Inference'
author: "Nathan Taback"
date: "June 13, 2025"
output: pdf_document
---
# Question

(\it Adapted from Box, Hunter, and Hunter) Fifteen judges were randomly allocated to judge one of two brands of beer, A or B, for taste.  Eight judges will be assigned to Brand A and seven judges to brand B.  The judges ranked the beer they tasted using  a 10-point (Likert) scale with 1 representing `poor taste' and 10 representing `outstanding taste'.

The table below shows the rating from each judge.  The number in brackets beside the rating indicates which judge gave the rating.  For example, judge 1 gave a rating of 2 to brand A, and judge 9 gave a rating of 3 to brand B.  In this question you will evaluate if there is "causal" evidence that Brand B tastes better than Brand A.

\begin{table}[htp]
\begin{center}
\begin{tabular}{c | c c c c c c c c}
Brand A & 2 (1) & 4 (2) & 2 (3) & 1 (4) & 9 (5) & 9 (6) & 2 (7) & 2 (10) \\
\hline
Brand B & 8 (8) & 3 (9) & 5 (11) & 3 (12) & 7 (13) &7 (14) & 4 (15)
\end{tabular}
\end{center}
\label{default}
\end{table}

Answer the following questions using a programming language such as R or Python. 


A.  What are the null and alternative hypotheses?
B.  What are the experimental units?  What are the treatments?
C.  How many values does the randomization distribution of the difference in **median** ratings between the two brands contain?
D.  Create a histogram of this randomization distribution.  
E.  Compute the P-value and interpret the P-value.
F.  Is there *causal evidence* that brand B tastes better than Brand A?  Explain.


